name: Docker Image Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1    
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release the Docker image
        run: make cross-build-container
